#!/usr/bin/env python
# coding: utf-8

import os
import SimpleHTTPServer
import SocketServer
import rospy

RESOURCE_PATH = os.path.join(os.path.dirname(__file__), '../resource')

def run_http_server(port):
    handler = SimpleHTTPServer.SimpleHTTPRequestHandler
    httpd = SocketServer.TCPServer(('', port), handler)
    httpd.serve_forever()

def main():
    rospy.init_node('web_server')

    port = int(rospy.get_param('~port', 8080))

    os.chdir(RESOURCE_PATH)
    run_http_server(port)

if __name__ == '__main__':
    main()
